version: 1.0.{build}

branches:
  only:
  - master

image: Visual Studio 2017

before_build:
- nuget restore
- choco install dotnetcore-sdk
- choco install codecov

build:
  project: WeeklyChallenge.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test  -output:".\MyProject_coverage.xml" -oldstyle

#upload report
- codecov -f ".\MyProject_coverage.xml"
